name: spotless-check

on:
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '.github/workflows/spotless.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for clone

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: ./.github/actions/setup-java

      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck
